<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn more_WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</name>
   <tag></tag>
   <elementGuidId>780b7114-deff-404b-ad13-5a70ea6b18fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.WpHeLc.VfPpkd-mRLv6.VfPpkd-RLmnJb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='next']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Try again&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b92981f2-c6f8-4a0e-9ec6-96b5f5d81db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</value>
      <webElementGuid>1e94d9c1-2bdf-43c3-9c7f-fb709cd2238f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/restart?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&amp;ddm=0&amp;dsh=S17056363%3A1718354989956754&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AS5LTATDgN_Ojbz0C2imlwflUdS-XT-jQy7tDbpQio168EmYdXUn_n8X0LExFeIB-lDb7EFEprwW0g&amp;rip=1&amp;service=mail</value>
      <webElementGuid>bf00e0bd-dcde-4a40-936e-3bb53949a295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Try again</value>
      <webElementGuid>55fc7804-c9ed-415e-9af8-c616fefe7a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navigation</name>
      <type>Main</type>
      <value>server</value>
      <webElementGuid>dc0790f3-456a-4713-9b42-c6c98d3956b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>hSRGPd</value>
      <webElementGuid>c29b453e-293c-454d-b443-45413ffe6ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next&quot;)/div[@class=&quot;VfPpkd-dgl2Hf-ppHlrf-sM5MNb&quot;]/div[@class=&quot;VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc LQeN7 BqKGqe Jskylb TrZEUc lw1w4b VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d&quot;]/a[@class=&quot;WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb&quot;]</value>
      <webElementGuid>06d9a8f0-63c3-4917-b851-609afe73fd72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='next']/div/div/a</value>
      <webElementGuid>886db39f-718e-4143-b7d6-0aa24bbbd504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/restart?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&amp;ddm=0&amp;dsh=S17056363%3A1718354989956754&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AS5LTATDgN_Ojbz0C2imlwflUdS-XT-jQy7tDbpQio168EmYdXUn_n8X0LExFeIB-lDb7EFEprwW0g&amp;rip=1&amp;service=mail')]</value>
      <webElementGuid>e1c42628-90c5-4694-bb88-b8fbd3e48712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>1c322bfb-e2a9-4477-85bd-3d67ce1cd964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/restart?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&amp;ddm=0&amp;dsh=S17056363%3A1718354989956754&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AS5LTATDgN_Ojbz0C2imlwflUdS-XT-jQy7tDbpQio168EmYdXUn_n8X0LExFeIB-lDb7EFEprwW0g&amp;rip=1&amp;service=mail']</value>
      <webElementGuid>52412661-f575-4d4c-89c5-91780804cbf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
