<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn more_WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb_1</name>
   <tag></tag>
   <elementGuidId>c513927f-7268-4720-a916-21912bed2011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.WpHeLc.VfPpkd-mRLv6.VfPpkd-RLmnJb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='next']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Try again&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07d9e6e9-2504-450d-a660-a1eb8c20b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</value>
      <webElementGuid>4745ffee-8a96-45cd-9a30-3ff93b49eaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/restart?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&amp;ddm=0&amp;dsh=S-1258000999%3A1718355035663356&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AS5LTAR7CUVUMX_XqqMDcWW3lLCtv2WFAlG_elyoRXcWkzQtx2hxXgagiZjyzKXsq54xRdTV5p9ZZw&amp;rip=1&amp;service=mail</value>
      <webElementGuid>a9dd1d86-5187-40de-8cf3-111c4c71fbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Try again</value>
      <webElementGuid>0f9e86e3-633b-455a-9868-543b8c603d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navigation</name>
      <type>Main</type>
      <value>server</value>
      <webElementGuid>149abfa8-3a08-48bc-9508-3244ba395d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>hSRGPd</value>
      <webElementGuid>c16ae182-38ac-4e1b-a724-a91f6ab683f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next&quot;)/div[@class=&quot;VfPpkd-dgl2Hf-ppHlrf-sM5MNb&quot;]/div[@class=&quot;VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc LQeN7 BqKGqe Jskylb TrZEUc lw1w4b VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d&quot;]/a[@class=&quot;WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb&quot;]</value>
      <webElementGuid>298e9c44-1b8d-435a-b270-4d083a781c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='next']/div/div/a</value>
      <webElementGuid>ab34b798-266d-4b90-b238-50db9a3b2bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/restart?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&amp;ddm=0&amp;dsh=S-1258000999%3A1718355035663356&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AS5LTAR7CUVUMX_XqqMDcWW3lLCtv2WFAlG_elyoRXcWkzQtx2hxXgagiZjyzKXsq54xRdTV5p9ZZw&amp;rip=1&amp;service=mail')]</value>
      <webElementGuid>7b4fef16-db87-4379-bc0c-226dd48d0c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>a2245d0f-11e1-431f-9df6-13b52d9e7a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/restart?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&amp;ddm=0&amp;dsh=S-1258000999%3A1718355035663356&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AS5LTAR7CUVUMX_XqqMDcWW3lLCtv2WFAlG_elyoRXcWkzQtx2hxXgagiZjyzKXsq54xRdTV5p9ZZw&amp;rip=1&amp;service=mail']</value>
      <webElementGuid>2c2a437f-fb43-413f-9246-c182c98ca1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
