<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Software TestingPadma Ramasamy - APA C_263271</name>
   <tag></tag>
   <elementGuidId>1382ed36-a636-46f9-8011-be6277e889af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=':7r']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Software TestingPadma Ramasamy - APA College, Oddanchatram - Sir, Github Uaername : Padmaramasamy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e29118aa-80e5-47cd-a1ac-024c8a4175d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:7r</value>
      <webElementGuid>ffa08a68-f3b1-41f5-8d06-3e0f06771de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bog</value>
      <webElementGuid>d92c086d-c2aa-4acd-aa4b-ea5a1ef5a99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Software TestingPadma Ramasamy - APA College, Oddanchatram</value>
      <webElementGuid>eae8fbba-5e0a-4222-938d-2a21731cd05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:7r&quot;)</value>
      <webElementGuid>410efaf4-71d9-4502-a1c5-0edefa92f26e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id=':7r']</value>
      <webElementGuid>6206f4bd-a642-4cff-bb96-24b68660ade3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id=':7p']/div/div/div/span</value>
      <webElementGuid>aaf151f1-09c6-4da4-a6b5-e3bc60bdcd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bharaniwebd.'])[2]/following::span[1]</value>
      <webElementGuid>b1b8c4e2-5bf0-44b4-beab-4ea65fdd9c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td[5]/div/div/div/span</value>
      <webElementGuid>49f7b6e3-4e49-411c-a54b-11f416f27765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = ':7r' and (text() = 'Software TestingPadma Ramasamy - APA College, Oddanchatram' or . = 'Software TestingPadma Ramasamy - APA College, Oddanchatram')]</value>
      <webElementGuid>60406452-5e60-4a4b-abd2-64a7659d573d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
